{% set name = "serializable" %}
{% set version = "0.2.1" %}
{% set sha256 = "ec604e5df0c1236c06d190043a407495c4412dd6b6fd3b45a8514518173ed961" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - pypandoc
  run:
    - python >={{ python_min }}
    - typechecks >=0.0.2
    - six >=1.9.0
    - simplejson

test:
  requires:
    - python {{ python_min }}
  imports:
    - serializable

about:
  home: https://github.com/iskandr/serializable
  license: Apache-2.0
  summary: 'Base class with serialization helpers for user-defined Python objects'
  license_family: Apache
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'

extra:
  recipe-maintainers:
    - npavlovikj
